export const GET_LIST_TABLECOMPONENT_ACTION = 'app/TableComponent/GET_LIST_TABLECOMPONENT_ACTION';
export const GET_LIST_TABLECOMPONENT_SUCCESS = 'app/TableComponent/GET_LIST_TABLECOMPONENT_SUCCESS';
export const GET_LIST_TABLECOMPONENT_FAILED = 'app/TableComponent/GET_LIST_TABLECOMPONENT_FAILED';
export const DELETE_TABLECOMPONENT_ACTION = 'app/TableComponent/DELETE_TABLECOMPONENT_ACTION';
export const DELETE_TABLECOMPONENT_SUCCESS = 'app/TableComponent/DELETE_TABLECOMPONENT_SUCCESS';
export const DELETE_TABLECOMPONENT_FAILED = 'app/TableComponent/DELETE_TABLECOMPONENT_FAILED';

export const RESET_ACTION = 'app/TableComponent/RESET_ACTION';
