export const GET_LIST_TABLECOMPONENT_ACTION = 'qlts/TableComponent/GET_LIST_TABLECOMPONENT_ACTION'; 
export const GET_LIST_TABLECOMPONENT_SUCCESS = 'qlts/TableComponent/GET_LIST_TABLECOMPONENT_SUCCESS';
export const GET_LIST_TABLECOMPONENT_FAILED = 'qlts/TableComponent/GET_LIST_TABLECOMPONENT_FAILED';
export const EDIT_TABLECOMPONENT_ACTION = 'qlts/TableComponent/EDIT_TABLECOMPONENT_ACTION';
export const EDIT_TABLECOMPONENT_SUCCESS = 'qlts/TableComponent/EDIT_TABLECOMPONENT_SUCCESS';
export const EDIT_TABLECOMPONENT_FAILED = 'qlts/TableComponent/EDIT_TABLECOMPONENT_FAILED';
export const DELETE_TABLECOMPONENT_ACTION = 'qlts/TableComponent/DELETE_TABLECOMPONENT_ACTION';
export const DELETE_TABLECOMPONENT_SUCCESS = 'qlts/TableComponent/DELETE_TABLECOMPONENT_SUCCESS'; 
export const DELETE_TABLECOMPONENT_FAILED = 'qlts/TableComponent/DELETE_TABLECOMPONENT_FAILED'; 

export const RESET_ACTION = 'qlts/TableComponent/RESET_ACTION'